import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKey:
    """`id` is a PostgreSQL uuid generated by the database."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )


class CreatedAt:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


class Timestamps(CreatedAt):
    """Mutable tables: creation and last-update time (timestamptz, default now())."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


def one_of(column: str, values: tuple[str, ...]) -> str:
    """SQL for a CHECK that limits a text column to a list of values."""
    return f"{column} IN ({', '.join(repr(v) for v in values)})"
